-- ==========================================================
--  CREATE TABLES SCRIPT (Full Variant with Legacy Tables)
--  Project: rx-back-end
--  Notes:
--    * Uses IDENTITY (no external sequences required)
--    * Creates annotation_event_log BEFORE trigger function
--    * Schema-qualified references inside the trigger
--    * Adds poller-friendly index
-- ==========================================================

BEGIN;

-- ==========================================================
-- 1. Table: public.user
-- ==========================================================
DROP TABLE IF EXISTS public."user" CASCADE;

CREATE TABLE public."user"
(
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(255) NOT NULL UNIQUE,
    password      varchar(255) NOT NULL,
    display_name  varchar(255),
    email         varchar(255),
    created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public."user" OWNER TO postgres;

-- ==========================================================
-- 2. Table: public.project
-- ==========================================================
DROP TABLE IF EXISTS public.project CASCADE;

CREATE TABLE public.project
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE,
    "desc"      text,
    created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.project OWNER TO postgres;

-- ==========================================================
-- 3. Table: public.permission
-- ==========================================================
DROP TABLE IF EXISTS public.permission CASCADE;

CREATE TABLE public.permission
(
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key   varchar(255) NOT NULL UNIQUE,
    "desc" text
);
ALTER TABLE public.permission OWNER TO postgres;

-- ==========================================================
-- 4. Table: public.project_user
-- ==========================================================
DROP TABLE IF EXISTS public.project_user CASCADE;

CREATE TABLE public.project_user
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proj_id    integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
    user_id    integer NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_user_proj_id_user_id_key UNIQUE (proj_id, user_id)
);
ALTER TABLE public.project_user OWNER TO postgres;

-- ==========================================================
-- 5. Table: public.project_user_permission
-- ==========================================================
DROP TABLE IF EXISTS public.project_user_permission CASCADE;

CREATE TABLE public.project_user_permission
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proj_id    integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
    user_id    integer NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
    perm_id    integer NOT NULL REFERENCES public.permission(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_user_permission_proj_id_user_id_perm_id_key UNIQUE (proj_id, user_id, perm_id)
);
ALTER TABLE public.project_user_permission OWNER TO postgres;

-- ==========================================================
-- 6. Table: public.room
-- ==========================================================
DROP TABLE IF EXISTS public.room CASCADE;

CREATE TABLE public.room
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE,
    "desc"      text,
    owner       integer REFERENCES public."user"(id),
    proj_id     integer REFERENCES public.project(id),
    is_closed   boolean NOT NULL DEFAULT false,
    created_by  integer REFERENCES public."user"(id),
    updated_by  integer REFERENCES public."user"(id),
    created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.room OWNER TO postgres;

-- ==========================================================
-- 7. Table: public.annotation
-- ==========================================================
DROP TABLE IF EXISTS public.annotation CASCADE;

CREATE TABLE public.annotation
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proj_id     integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
    doc_id      varchar(255) NOT NULL,
    data        text,
    created_by  integer REFERENCES public."user"(id),
    updated_by  integer REFERENCES public."user"(id),
    is_deleted  boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    room_id     text
);
ALTER TABLE public.annotation OWNER TO postgres;

-- ==========================================================
-- 8. Table: public.annotation_event_log  (CREATE BEFORE FUNCTION)
-- ==========================================================
DROP TABLE IF EXISTS public.annotation_event_log CASCADE;

CREATE TABLE public.annotation_event_log
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   varchar(255) NOT NULL,
    event_data   jsonb NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamptz
);
ALTER TABLE public.annotation_event_log OWNER TO postgres;

-- Poller index for: processed_at IS NULL AND event_type = 'add_annotation' ORDER BY created_at
CREATE INDEX IF NOT EXISTS idx_annotation_event_log_pending
  ON public.annotation_event_log (event_type, created_at)
  WHERE processed_at IS NULL;

-- ==========================================================
-- 9. Function: public.trg_after_annotation_insert_func()
--    (Schema-qualified + NULL-safe room_id check)
-- ==========================================================
DROP FUNCTION IF EXISTS public.trg_after_annotation_insert_func() CASCADE;

CREATE OR REPLACE FUNCTION public.trg_after_annotation_insert_func()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.room_id IS NULL OR NEW.room_id = '' THEN
        INSERT INTO public.annotation_event_log (event_type, event_data)
        VALUES ('add_annotation', to_jsonb(NEW));
    END IF;
    RETURN NEW;
END;
$$;
ALTER FUNCTION public.trg_after_annotation_insert_func() OWNER TO postgres;

-- ==========================================================
-- 10. Trigger: trg_after_annotation_insert
-- ==========================================================
DROP TRIGGER IF EXISTS trg_after_annotation_insert ON public.annotation;

CREATE TRIGGER trg_after_annotation_insert
AFTER INSERT ON public.annotation
FOR EACH ROW
EXECUTE FUNCTION public.trg_after_annotation_insert_func();

-- ==========================================================
-- 11. Table: public.measurement
-- ==========================================================
DROP TABLE IF EXISTS public.measurement CASCADE;

CREATE TABLE public.measurement
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proj_id     integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
    data        text,
    created_by  integer REFERENCES public."user"(id),
    updated_by  integer REFERENCES public."user"(id),
    is_deleted  boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.measurement OWNER TO postgres;

-- ==========================================================
-- 12. Legacy Table: public.stamp_template
-- ==========================================================
DROP TABLE IF EXISTS public.stamp_template CASCADE;

CREATE TABLE public.stamp_template
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE,
    type        text NOT NULL,
    "desc"      text,
    data        text NOT NULL,
    created_by  integer REFERENCES public."user"(id),
    updated_by  integer REFERENCES public."user"(id),
    created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.stamp_template OWNER TO postgres;

-- ==========================================================
-- 13. Legacy View: public.project_annotation
-- ==========================================================
DROP VIEW IF EXISTS public.project_annotation CASCADE;

CREATE VIEW public.project_annotation AS
SELECT
    a.id         AS anno_id,
    a.created_by,
    a.updated_by,
    a.created_at,
    a.updated_at,
    p.id         AS proj_id,
    p.name       AS proj_name,
    p."desc"     AS proj_desc
FROM public.annotation a
JOIN public.project   p ON a.proj_id = p.id;

COMMIT;
